version: '3.8'

services:
  api:
    container_name: fast-api
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    ports:
      - "8000:80"
    volumes:
      - ./app:/code/app
      - ./requirements.txt:/code/requirements.txt
    environment:
      PYTHONUNBUFFERED: 1
      PYTHONPATH: /code/app
